---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This is a large single nuclei RNA-seq dataset generated by Evangelyn Sim and Enzo Porrello from the Heart Regeneration group at the Murdoch Children's Research Institute (MCRI). The samples were prepared by Evangelyn Sim and the data was processed and sequenced at the Translational Genomics Unit at MCRI.

The samples are heart biopsies from the left ventricle from three different developmental stages: fetal (n=3), child (n=3) and adult (n=3). Males and females were profiled in order to understand sex differences in the developing heart. There are several aspects of the analysis:

* define the cell types present at each of the developmental stages
* analyse differences in cell type composition across development
* perform differential expression analysis across the developmental trajectory 
within each broad cell type
* perform differential expression analysis between males and females to 
understand how sex plays a role in normal heart development
